site_name: Bhavya Maheshwari's website

repo_url: https://github.com/mbhavya/mbhavya.github.io
repo_name: github.com/mbhavya

theme:
  name: material
  language: en
  features:
    - content.tabs.link
    - content.code.annotate
    - content.tooltips
    - navigation.tabs
    - navigation.instant
    #- navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.top
  social:
    - type: 'github'
      link: 'https://github.com/mbhavya'
      
extra_css: ["extra.css"]    
  # icon:
  #   repo: fontawesome/brands/github
extra:
    default: stable

plugins:
  - search

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

      