site_name: Bhavya Maheshwari's website

repo_url: https://github.com/mbhavya/mbhavya.github.io
repo_name: github.com/mbhavya
edit_uri: edit/main/docs
theme:
  name: material
  language: en
  features:
    - content.tabs.link
    - content.code.annotate
    - content.tooltips
    - navigation.tabs
    - navigation.instant
    #- navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.top
  social:
    - type: 'github'
      link: 'https://github.com/mbhavya'
      
extra_css: ["extra.css"]    
  # icon:
  #   repo: fontawesome/brands/github
extra:
    default: stable

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true


markdown_extensions:
  - meta
  - abbr
  - attr_list
  - admonition
  - footnotes
  - pymdownx.smartsymbols
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Playground:
    - Cloud Native:
      - Ory Oathkeeper: cloud_native/oathkeeper.md
      - Open Telemetry: cloud_native/otel.md
      - knative: cloud_native/knative.md
    - Distributed Computing:
      - Dask: distributed_computing/dask.md
      - Ray: distributed_computing/ray.md 
    - Data Science:
      - Rasa: data_science/rasa.md
    - Data Engineering:
      - Prefect: data_engineering/prefect.md
      - DatahubProject: data_engineering/datahubproject.md
    - Tech Stuff:
      - API Contracts: tech_stuff/pact.md
      - Kubernetes Utilities: tech_stuff/k8s_utils.md